name: tdd_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  dio: ^4.0.4
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  faker: ^2.0.0
  test: ^1.17.12
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
